typography_spectrum: 0.2503940158057958
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45451471605338156
  lightness: 0.9481819397769868
  saturation: 0.8312200419604778
  rhythmicContrast: 0.9280377111863345
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27849981375038624
analytics:
  google: null
  facebook: null
  twitter: null
name: Travel Simplicity
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'DREAM BIG, THERE IS NO BOX.'
purpose: []
